=== BCDA-APS/pvWebMonitor/src/pvWebMonitor/pvlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
XML Schema to validate the pvlist.xml file

# Copyright (c) 2005-2022, University of Chicago, The Regents of the University of California, and Berliner Elektronenspeicherring Gesellschaft fuer Synchrotronstrahlung m.b.H. (BESSY) All rights reserved.
# See LICENSE file for details.
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  
  <xs:element name="pvwatch">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="definition" type="definition_type" maxOccurs="unbounded" minOccurs="0" />
        <xs:element name="EPICS_PV" type="pv_type" maxOccurs="unbounded" />
      </xs:sequence>
      
      <xs:attributeGroup ref="version_type" />
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="definition_type" mixed="true">
    <!-- used to tell humans what the terms mean in a pvlist.xml file -->
    <xs:attribute name="name" use="required" type="xs:NCName" />
  </xs:complexType>
  
  <xs:complexType name="pv_type">
    <!-- defines the declaration of one PV to be monitored -->
    <xs:attribute name="PV" type="xs:NMTOKEN" use="required" />
    <xs:attribute name="description" type="xs:string" use="required" />
    <xs:attribute name="display_format" type="xs:string" use="optional" default="%s" />
    <xs:attribute name="mne" type="xs:NCName" use="required" />
    <xs:attribute name="_ignore_" type="xs:boolean" use="optional" default="false" />
    <xs:attribute name="as_string" type="xs:boolean" use="optional" default="false" />
  </xs:complexType>
  
  <xs:attributeGroup name="version_type">
    <xs:attribute name="version" use="required">
      <!-- allowed version(s) of the config.xml format -->
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <!-- only allowed version -->
          <xs:enumeration value="1.0" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:attributeGroup>
  
</xs:schema>

=== BCDA-APS/pvWebMonitor/src/pvWebMonitor/project/pvlist.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="pvlist.xsl" ?>

<!-- You can edit this file with a text editor -->

<pvwatch version="1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="local_schema pvlist.xsd">
	<!-- (update version if format of XML file changes) -->

  <definition name="mne">
  	one-word mnemonic reference used in python and xslt code
  	(mne should be unique for each EPICS_PV)
  </definition>
  <definition name="PV">
  	EPICS process variable name (must be used in only one EPICS_PV)
  </definition>
  <definition name="description">
  	useful text informative to others
  </definition>
  <definition name="display_format">
  	(optional, default="%s") PVs will be formatted for display with this string
  </definition>
  <definition name="_ignore_">
  	(optional, default="false") this PV is ignored if value is not "false"
  </definition>


  <EPICS_PV PV="morel:TOD" 				description="IOC current time"  	mne="tod"/>
  <EPICS_PV PV="morel:STARTTOD" 		description="IOC boot time"  		mne="starttod"/>
  <EPICS_PV PV="morel:UPTIME" 			description="time IOC running"  	mne="uptime"/>
  <EPICS_PV PV="morel:HOSTNAME"			description="IOC host name" 		mne="hostname"/>
  <EPICS_PV PV="morel:ENGINEER"			description="engineer" 				mne="engineer"/>

  <EPICS_PV PV="morel:m1.RBV"   description="VDM_Stripe motor"             mne="VDM_Stripe"     display_format="%.3f"/>
  <EPICS_PV PV="morel:m1.VAL"   description="VDM_Stripe motor target"      mne="VDM_Stripe_VAL" display_format="%.3f"/>
  <EPICS_PV PV="morel:m1.DMOV"  description="VDM_Stripe motor done moving" mne="VDM_Stripe_DMOV"/>
  <EPICS_PV PV="morel:m2.RBV"   description="DCM_theta motor"              mne="DCM_theta"      display_format="%.6f"/>
  <EPICS_PV PV="morel:m2.VAL"   description="DCM_theta motor target"       mne="DCM_theta_VAL"  display_format="%.6f"/>
  <EPICS_PV PV="morel:m2.DMOV"  description="DCM_theta motor done moving"  mne="DCM_theta_DMOV"/>

  <EPICS_PV PV="morel:alldone" description="all motors done moving" mne="motors_alldone"/>
  <EPICS_PV PV="morel:moving" description="number of motors moving" mne="motors_moving"/>

</pvwatch>
